/**
 * Created by Raphael Karanja on 2019-03-04.
 */

//AUTH
export const LOGIN_USER_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED';

//EVENTS
export const ADDED_AN_EVENT = 'ADDED_AN_EVENT';